<div class="block block-new-customer">
    <div class="block-title">
		<h2 class="title" id="block-new-customer-heading" role="heading" aria-level="2"><span><?php /* @escapeNotVerified */ echo __('New Customers') ?></span></h2>
    </div>
    <div class="block-content" aria-labelledby="block-new-customer-heading">
        <p><?php /* @escapeNotVerified */ echo __('We would love to have you as a customer. Please send us an email at <a href="mailto:info@i-catchers.eu"> info@i-catchers.eu </a> with your company details and your contact number. We will add you in our system database.') ?></p>
    </div>
</div>