<?php
/**
 * @var $block \Catchers\CatalogImageGrid\Block\Category\Widget\CategoryList
 */
?>
<div class="category-widget-main">
    <div class="category">
        <?php $_category = $block->getCategory(); ?>
        <?php foreach($_category as $category): ?>
            <div class="category-list">
                <a href="<?php echo $category->getUrl(); ?>">
                    <?php if($category->getImageUrl()): ?>
                        <?php $imageResize = $block->getResize($category->getImage(), 262, 262);?>
                        <span class="cat-image"><img src="<?php echo $imageResize; ?>" alt="<?php echo $block->escapeHtml($category->getName()) ?>" /></span>
                    <?php else: ?>
                        <span class="cat-image"><img src="<?php echo $block->getPlaceHolderImage(); ?>" alt="<?php echo $block->escapeHtml($category->getName()) ?>" /></span>
                    <?php endif; ?>
                    <span class="cat-name"><?php echo $category->getName(); ?></span>
                </a>
            </div>
        <?php endforeach; ?>
    </div>
</div>
