<?php
/**
 * ||GEISSWEB| EU VAT Enhanced
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the GEISSWEB End User License Agreement
 * that is available through the world-wide-web at this URL: https://www.geissweb.de/legal-information/eula
 *
 * DISCLAIMER
 *
 * Do not edit this file if you wish to update the extension in the future. If you wish to customize the extension
 * for your needs please refer to our support for more information.
 *
 * @copyright   Copyright (c) 2015 GEISS Weblösungen (https://www.geissweb.de)
 * @license     https://www.geissweb.de/legal-information/eula GEISSWEB End User License Agreement
 */

namespace Geissweb\Euvat\Plugin\Adminhtml\Form;

use Geissweb\Euvat\Helper\Configuration;
use Magento\Framework\View\Element\UiComponentInterface;

/**
 * Class CustomerAddress
 */
class CustomerAddress
{
    /**
     * @var Configuration
     */
    public $configHelper;

    /**
     * CheckoutLayout constructor.
     *
     * @param Configuration $config
     */
    public function __construct(
        Configuration $config
    ) {
        $this->configHelper = $config;
    }

    /**
     * Adds the vat_id field JS configuration
     *
     * @param                      $subject
     * @param UiComponentInterface $component
     *
     * @throws \Magento\Framework\Exception\NoSuchEntityException
     */
    public function beforeRegister($subject, UiComponentInterface $component)
    {
        // Appears only on the address form
        if ($component->getName() === 'vat_id') {
            $baseConfig = $component->getData('config');
            $additionalConfig = $this->configHelper->getAdminVatFieldConfig();
            $finalConfig = array_merge($baseConfig, $additionalConfig);
            $component->setData('config', $finalConfig);
        }
    }
}
