<table class="data table stocks" id="product-stocks-table">
    <tbody>
        <tr>
            <?php foreach($this->getAttributes() as $attribute): ?>
                    <th class="col label" scope="row"><?php echo $attribute->getLabel(); ?></th>
            <?php endforeach; ?>
            <?php foreach($this->getWarehouses() as $warehouse): ?>
                    <th class="col label" scope="row"><?php echo $warehouse->getw_name(); ?></th>
            <?php endforeach; ?>
        </tr>
        <?php foreach($this->getChildren() as $child): ?>
            <tr>
                <?php foreach($this->getAttributes() as $attribute): ?>
                    <td><?php echo $child->getAttributeText($attribute->getProductAttribute()->getattribute_code()); ?></td>
                <?php endforeach; ?>
                <?php foreach($this->getWarehouses() as $warehouse): ?>
                    <td><?php echo $this->getStock($child->getId(), $warehouse->getId()); ?></td>
                <?php endforeach; ?>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>
