<?php
/**
 * ||GEISSWEB| EU VAT Enhanced
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the GEISSWEB End User License Agreement
 * that is available through the world-wide-web at this URL: https://www.geissweb.de/legal-information/eula
 *
 * DISCLAIMER
 *
 * Do not edit this file if you wish to update the extension in the future. If you wish to customize the extension
 * for your needs please refer to our support for more information.
 *
 * @copyright   Copyright (c) 2015 GEISS Weblösungen (https://www.geissweb.de)
 * @license     https://www.geissweb.de/legal-information/eula GEISSWEB End User License Agreement
 */

namespace Geissweb\Euvat\Model\Validation;

use Geissweb\Euvat\Logger\Logger;

/**
 * Class Base
 * A base class to handle service validation process
 */
class Base
{
    /**
     * Endpoint to connect to
     * @var $serviceUrl
     */
    public $serviceUrl;

    /**
     * Service client
     * @var $client
     */
    public $client;

    /**
     * Logger
     * @var Logger
     */
    public $logger;

    /**
     * Holder for validation params
     * @var array
     */
    public $params = [];

    /**
     * Service result
     * @var \Geissweb\Euvat\Api\Data\ValidationResultInterface
     */
    public $validationResult;

    /**
     * @var ResultFactory
     */
    public $validationResultFactory;

    /**
     * @var \Magento\Framework\App\Request\Http
     */
    public $request;

    /**
     * @var \Geissweb\Euvat\Helper\Configuration
     */
    public $configHelper;

    /**
     * @var \Magento\Framework\HTTP\Client\Curl
     */
    public $curlClient;

    /**
     * Service constructor
     *
     * @param \Geissweb\Euvat\Logger\Logger                  $logger
     * @param \Geissweb\Euvat\Helper\Configuration           $configHelper
     * @param \Magento\Framework\App\Request\Http            $request
     * @param \Magento\Framework\HTTP\Client\Curl            $curlClient
     * @param \Geissweb\Euvat\Model\Validation\ResultFactory $validationResultFactory
     */
    public function __construct(
        \Geissweb\Euvat\Logger\Logger $logger,
        \Geissweb\Euvat\Helper\Configuration $configHelper,
        \Magento\Framework\App\Request\Http $request,
        \Magento\Framework\HTTP\Client\Curl $curlClient,
        \Geissweb\Euvat\Model\Validation\ResultFactory $validationResultFactory
    ) {
        $this->logger = $logger;
        $this->configHelper = $configHelper;
        $this->request = $request;
        $this->curlClient = $curlClient;

        $this->validationResultFactory = $validationResultFactory;
        $this->validationResult = $this->validationResultFactory->create();
        $this->validationResult
                    ->setRequesterCountryCode($this->configHelper->getMerchantCountryCode())
                    ->setRequesterNumber($this->configHelper->getMerchantVatNumber())
                    ->setHandle($this->request->getParam('handle'))
                    ->setVatRequestSuccess(false)
                    ->setVatIsValid(false)
                    ->setVatRequestId('INIT');

        $this->setParam('requesterCountryCode', $this->configHelper->getMerchantCountryCode());
        $this->setParam('requesterVatNumber', $this->configHelper->getMerchantVatNumber());
    }

    /**
     * Sets validation parameters
     *
     * @param string $key
     * @param string $value
     *
     * @return void
     */
    public function setParam($key, $value)
    {
        $this->params[$key] = $value;
    }

    /**
     * Gets validation parameters
     *
     * @param string $key
     *
     * @return string
     */
    public function getParam(string $key)
    {
        return $this->params[$key];
    }

    /**
     * Gets validation parameters
     * @return array
     */
    public function getParams()
    {
        return $this->params;
    }

    /**
     * Returns validation result
     * @return \Geissweb\Euvat\Model\Validation\Result|\Geissweb\Euvat\Api\Data\ValidationResultInterface
     */
    public function getResult()
    {
        return $this->validationResult;
    }

    /**
     * Returns offline validation result
     * @return \Geissweb\Euvat\Model\Validation\Result
     */
    public function getOfflineResult()
    {
        /** @var \Geissweb\Euvat\Model\Validation\Result $offlineValidationResult */
        $offlineValidationResult = $this->validationResultFactory->create();
        $offlineValidationResult
            ->setRequesterCountryCode($this->configHelper->getMerchantCountryCode())
            ->setRequesterNumber($this->configHelper->getMerchantVatNumber())
            ->setHandle($this->request->getParam('handle'))
            ->setVatId($this->params['vatNumber'])
            ->setVatIsValid(true)
            ->setVatRequestCountryCode($this->params['countryCode'])
            ->setVatRequestDate(date("Y-m-d H:i:s"))
            ->setVatRequestId('OFFLINE')
            ->setVatRequestSuccess(false)
            ->setVatTraderName('')
            ->setVatTraderAddress('')
            ->setVatTraderCompanyType('')
            ->setRequestMessage(__('The VAT number is valid.'));
        return $offlineValidationResult;
    }


    /**
     * Check if service is online
     * @return bool
     */
    public function isOnline()
    {
        $this->curlClient->setOptions([
            CURLOPT_RETURNTRANSFER => false,
            CURLOPT_VERBOSE => false,
            CURLOPT_IPRESOLVE => CURL_IPRESOLVE_V4,
            CURLOPT_TIMEOUT => 10
        ]);
        $this->curlClient->get($this->serviceUrl);
        $httpcode = $this->curlClient->getStatus();
        if ($httpcode == "200") {
            $this->logger->debug("BaseValidation::isOnline TRUE");
            return true;
        } else {
            $this->logger->debug("BaseValidation::isOnline FALSE ($httpcode)");
            return false;
        }
    }
}
