<!--
<!--
/**
 * Created By : TheCoachSMB - Sonal Motghare-Balpande
 */
-->
<div class="carousel-wrap">
  <div class="owl-carousel">
	<div class="item" style="heigh:auto"><img src="https://www.mocadi.store/pub/media/wysiwyg/1_1.jpg"></div>
	<div class="item" style="heigh:auto"><img src="https://www.mocadi.store/pub/media/wysiwyg/1_1.jpg"></div>
	<div class="item" style="heigh:auto"><img src="https://www.mocadi.store/pub/media/wysiwyg/1_1.jpg"></div>
	<div class="item" style="heigh:auto"><img src="https://www.mocadi.store/pub/media/wysiwyg/1_1.jpg"></div>
	<div class="item" style="heigh:auto"><img src="https://www.mocadi.store/pub/media/wysiwyg/1_1.jpg"></div>
	<div class="item" style="heigh:auto"><img src="https://www.mocadi.store/pub/media/wysiwyg/1_1.jpg"></div>
  </div>
</div>