<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Product list toolbar
 *
 * @var $block \Magento\Catalog\Block\Product\ProductList\Toolbar
 */
use Magento\Catalog\Model\Product\ProductList\Toolbar;
//echo "this is toolbnar";
?>
<?php if ($block->getCollection()->getSize()):

          /*var_dump($block->getCollection()->getSize());
          exit;
*/

?>
    <div class="toolbar toolbar-products event-toolbar" style="position: inherit;" data-mage-init='<?= /* @escapeNotVerified */ $block->getWidgetOptionsJson() ?>'>
        <?php if ($block->isExpanded()): ?>
            <?php include ($block->getTemplateFile('Mageants_EventManager::product/list/toolbar/viewmode.phtml')) ?>
        <?php endif; ?>

        <?php include ($block->getTemplateFile('Mageants_EventManager::product/list/toolbar/amount.phtml')) ?>

        <?= $block->getPagerHtml() ?>

         <!-- <?php //include ($block->getTemplateFile('Mageants_EventManager::product/list/toolbar/limiter.phtml')) ?> -->

        <?php if ($block->isExpanded()): ?>
            <?php include ($block->getTemplateFile('Mageants_EventManager::product/list/toolbar/sorter.phtml')) ?>
        <?php endif; ?>
    </div>
<?php endif ?>
