<?php 
$helper = $this->helper('Magepow\Flipbook\Helper\Data');
$isEnabled      = $helper->getConfigModule('general/enabled');
$books = $this->getCollection();
$layout = $this->getThemeLayout();
if(!$isEnabled) return;
?>

<?php 
	if ($layout == 1) {
		$class = 'col-lg-12 col-md-12';
	}
	elseif ($layout == 2) {
		$class = 'col-md-6 col-sm-6 col-xs-12';
	}

	elseif ($layout == 3) {
		$class = 'col-md-4 col-sm-4 col-xs-12';
	}
	else {
		$class = 'col-md-3 col-sm-3 col-xs-12';
	}
?>

<div class="container">
	<div class="row">
		<div class="flipbook">
		<?php foreach ($books as $book): ?>
			<div class="flipbookbanner">
				<div class="<?php echo $class ?>">
					<a href="<?php echo $book->getData('external_link'); ?>" target="_blank"><?php echo $this->getThumbnail($book); ?></a>
				</div>	
			</div>
		<?php endforeach; ?>
		</div>
	</div>
</div>