<script>
        var OrganizerEditTaskUrl = '<?php echo $this->getUrl('organizer/organizer/edit', ['current' => true]); ?>';
        var OrganizerSaveTaskUrl = '<?php echo $this->getUrl('organizer/organizer/save', ['current' => true]); ?>';
        var OrganizerSaveNotifyTaskUrl = '<?php echo $this->getUrl('organizer/organizer/save', ['current' => true,'notify' => 1]); ?>';
        var OrganizerDeleteTaskUrl = '<?php echo $this->getUrl('organizer/organizer/delete', ['current' => true]); ?>';
</script>
